name: PlayerVaults
main: com.drtshock.playervaults.PlayerVaults
authors: [drtshock, gomeow, Chester]
version: ${project.version}-b${BUILD_NUMBER}
website: http://dev.bukkit.org/server-mods/PlayerVaults
softdepend: [Vault]
commands:
  pv:
    description: Open a vault with /vault <number>
    aliases: [vault]
  pvdel:
    description: Delete a vault.
    aliases: [vaultdel]
  pvsign:
    description: Delete a vault.
    aliases: [vaultsign]
  workbench:
    description: Opens a workbench.
    aliases: [wb]